# LAB 01 - Numpy

## #05. 기초통계량

### 라이브러리 참조

In [1]:
import numpy as np

### 샘플 데이터 생성

In [2]:
myarr = np.array([98,72,80,64,88,65,79,59,81,74])
myarr

array([98, 72, 80, 64, 88, 65, 79, 59, 81, 74])

### 데이터의위치·분포를 나타내는 기초통계량(1)

#### 총도수

In [3]:
print("총 도수",len(myarr))

총 도수 10


#### 최대, 최소, 합계

In [4]:
print("최대값:",np.max(myarr))
print("최소값:",np.min(myarr))
print("합계",np.sum(myarr))

최대값: 98
최소값: 59
합계 760


### 데이터의위치·분포를나타내는기초통계량(2)

In [5]:
print("평균",np.average(myarr))

평균 76.0


### 데이터의위치·분포를나타내는기초통계량(4)
#### ☐ 중앙값 (직접 구하기)

In [10]:
size = len(myarr) # 전체 데이터 수
sorted_arr = np.sort(myarr) # 순서대로 정렬
print("정렬:",sorted_arr)

#짝수인 경우 가운데 두 수의 평균
if size%2==0:
    p = (size//2) - 1 # 인덱스가 0부터 시작하므로 -1
    q = p+1 #p번째 다음 요소의 인덱스
    median = (sorted_arr[p]+sorted_arr[q])/2
else:
    p = size//2
    median = sorted_arr[p]

print("중앙값:",median)

정렬: [59 64 65 72 74 79 80 81 88 98]
중앙값: 76.5


### 데이터의위치·분포를나타내는기초통계량(5)
#### ☐ 중앙값 (NumPyAPI사용)

In [11]:
print("중앙값:",np.median(myarr))

중앙값: 76.5


### 데이터의위치·분포를나타내는기초통계량(9)
#### 1사분위 수

In [12]:
x = np.sort(myarr)
n = len(x)
q1_pos = (n-1)*0.25
i = int(np.floor(q1_pos))
f = q1_pos - i

#보간
Q1 = x[i] + f *(x[i+1]-x[i])
print("직접 계산한 1사분위수 (Q1):",Q1)

#numpy 내장 함수와 비교
print("Numpy로 계산한 1사분위수:",np.quantile(myarr,0.25))

직접 계산한 1사분위수 (Q1): 66.75
Numpy로 계산한 1사분위수: 66.75


### 데이터의위치·분포를나타내는기초통계량(12)
#### 3사분위 수

In [13]:
x = np.sort(myarr)
n = len(x)
q3_pos = (n-1)*0.75
i = int(np.floor(q3_pos))
f = q3_pos - i

#보간
Q3 = x[i]+f*(x[i+1]-x[i])
print("직접 계산한 1사분위 수(Q1)",Q3)

#numpy 내장 함수와 비교
print("Numpy로 계사난 1사분위수:",np.quantile(myarr,0.75))

직접 계산한 1사분위 수(Q1) 80.75
Numpy로 계사난 1사분위수: 80.75


### 데이터의범위·산포를나타내는기초통계량(1)
#### 데이터 구간 (𝑅𝑎𝑛𝑔𝑒)

In [14]:
print("데이터 구간",np.max(myarr)-np.min(myarr))

데이터 구간 39


### 데이터의범위·산포를나타내는기초통계량(2)

#### 사분위수 구간(𝐼𝑄𝑅)

In [15]:
print("사분위수 구간(IQR):",np.quantile(myarr,0.75)-np.quantile(myarr,0.25))

사분위수 구간(IQR): 14.0


### 데이터의범위·산포를나타내는기초통계량(4)
####  분산,표준편차

In [16]:
print("분산:",np.var(myarr))
print("표준편차:",np.std(myarr))

분산: 125.2
표준편차: 11.189280584559492


### 2차원배열의기초통계량(1)
#### 각 열끼리 연산(세로 연산)

In [18]:
mydata = np.array([[98,72,92,52,12],
                    [12,53,12,45,56]])

s1 = np.sum(mydata, axis = 0)
print(type(s1))
s1

<class 'numpy.ndarray'>


array([110, 125, 104,  97,  68])

#### 각 행끼리 연산 (가로 연산)

In [19]:
s2 = np.sum(mydata, axis = 1)
print(type(s2))
s2

<class 'numpy.ndarray'>


array([326, 178])