# LAB 01 - Data Analysis Overview / Numpy Library [1]

## #03. 그밖의 ndarray 형태

### 라이브러리 참조

In [1]:
import numpy as np

### 2차원 배열

In [7]:
import numpy as np

myarray = np.array([[98, 12, 23, 54], [32, 53, 21, 76], [12, 67, 87, 43]])

print(myarray)

print("차원크기", myarray.ndim)
print("차원별 원소수", myarray.shape)
print("원소의 데이터 타입:", myarray.dtype)

[[98 12 23 54]
 [32 53 21 76]
 [12 67 87 43]]
차원크기 2
차원별 원소수 (3, 4)
원소의 데이터 타입: int64


### boolean타입으로인덱싱

In [8]:
bool_array = np.array(
    [[True, False, True, False], [True, True, True, False], [True, True, True, False]]
)

In [9]:
result1 = myarray = myarray[bool_array]
result1

array([98, 23, 32, 53, 21, 12, 67, 87])

### 비교식에의한검색

In [11]:
result2 = myarray[myarray >= 80]
result2

array([98, 87])

In [12]:
result3 = myarray[np.logical_and(myarray >= 80, myarray <= 90)]
result3

array([87])

In [13]:
result4 = myarray[np.logical_or(myarray < 80, myarray > 90)]
result4

array([98, 23, 32, 53, 21, 12, 67])

### 정형화된배열생성

In [14]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.full([3, 4], 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [18]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### 랜덤배열(1)

In [20]:
np.random.rand(10)

array([0.39788166, 0.17253967, 0.00750285, 0.9829478 , 0.64960626,
       0.80283611, 0.06771047, 0.2810866 , 0.08268146, 0.04802548])

In [21]:
np.random.rand(4, 3)

array([[0.46384393, 0.27365667, 0.16779483],
       [0.17991585, 0.6324318 , 0.58695239],
       [0.34637198, 0.76893588, 0.34781884],
       [0.73280971, 0.45025092, 0.34880305]])

### 주어진범위안에서정수값을갖는랜덤배열

In [24]:
np.random.randint(0, 9, 10)

array([7, 5, 0, 2, 6, 5, 0, 3, 6, 5])

In [25]:
np.random.randint(0, 9, (3, 4))

array([[2, 5, 1, 4],
       [8, 0, 6, 0],
       [1, 1, 7, 4]])

### 랜덤 시드 고정

In [27]:
np.random.seed(1234)
np.random.normal(0, 1, (4, 3))

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])

In [28]:
np.random.normal(0, 1, (4, 3))

array([[ 0.95332413, -2.02125482, -0.33407737],
       [ 0.00211836,  0.40545341,  0.28909194],
       [ 1.32115819, -1.54690555, -0.20264632],
       [-0.65596934,  0.19342138,  0.55343891]])

### 표준정규분포를따르는랜덤배열

In [30]:
np.random.randn(10)

array([ 1.31815155, -0.46930528,  0.67555409, -1.81702723, -0.18310854,
        1.05896919, -0.39784023,  0.33743765,  1.04757857,  1.04593826])

In [31]:
np.random.randn(4, 3)

array([[ 0.86371729, -0.12209157,  0.12471295],
       [-0.32279481,  0.84167471,  2.39096052],
       [ 0.07619959, -0.56644593,  0.03614194],
       [-2.0749776 ,  0.2477922 , -0.89715678]])