# LAB 01 - Numpy Library [1]

## #04. 𝑛𝑑𝑎𝑟𝑟𝑎𝑦 형태 변환

### 라이브러리 참조

In [2]:
import numpy as np

In [3]:
### 원소의데이터타입변환[1]‒𝑎𝑠𝑡𝑦𝑝𝑒()함수사용

In [4]:
arr1 = np.arange(10)
print("원본배열:",arr1)
print("원본배열의 데이터 타입",arr1.dtype)

원본배열: [0 1 2 3 4 5 6 7 8 9]
원본배열의 데이터 타입 int64


In [5]:
arr2 = arr1.astype('float')
print("형변환 후의 배열:",arr2)
print("변환된 배열의 데이터 타입:",arr2.dtype)

형변환 후의 배열: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
변환된 배열의 데이터 타입: float64


In [6]:
arr3 = arr1.astype('str')
print("형변환 후의 배열:",arr3)
print("변환된 배열의 데이터 타입:",arr3.dtype)

형변환 후의 배열: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
변환된 배열의 데이터 타입: <U21


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 원소의데이터타입변환[2]‒𝑎𝑠𝑎𝑟𝑟𝑎𝑦()함수사용

In [7]:
arr1 = np.arange(10,20)
print("원본배열:",arr1)
print("원본배열의 데이터 타입",arr1.dtype)

원본배열: [10 11 12 13 14 15 16 17 18 19]
원본배열의 데이터 타입 int64


In [8]:
arr2 = np.asarray(arr1,dtype='float')
print("형변환 후의 배열:",arr2)
print("변환된 배열의 데이터 타입:",arr2.dtype)

형변환 후의 배열: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
변환된 배열의 데이터 타입: float64


In [9]:
arr3 = np.asarray(arr1,dtype='str')
print("형변환 후의 배열:",arr3)
print("변환된 배열의 데이터 타입:",arr3.dtype)

형변환 후의 배열: ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19']
변환된 배열의 데이터 타입: <U21


### 차원변환‒𝑟𝑒𝑠ℎ𝑎𝑝𝑒()함수

In [10]:
orgin = np.arange(20)
orgin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
x = orgin.reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
### orgin.reshape(3,7)
### 원소가 넘거나 모자란 경우 에러 발생

In [13]:
origin = np.array([[0,1,2,3,4],
                 [5,6,7,8,9],
                 [10,11,12,13,14],
                 [15,16,17,18,19]])

origin

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
y = origin.reshape(20)

In [15]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
rows,cols = origin.shape
rows,cols

(4, 5)

In [17]:
z = origin.reshape(rows*cols)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
origin = np.array([[0,1,2,3],
                 [4,5,6,7],
                 [8,9,10,11]])

origin

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
x = origin.reshape(-1,1)
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [20]:
y = origin.reshape(-1,2)

In [21]:
y

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [22]:
origin = np.arange(12)

In [23]:
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
x = origin.reshape(1,-1)

In [25]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [26]:
y = origin.reshape(2,-1)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [27]:
origin = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
print(origin)

x=origin.reshape(-1)
x

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])