# LAB 01 - Numpy Librady [1]

## #01 Numpy 시작하기

### 라이브러리 참조하기

In [1]:
import numpy as np

### 배열 생성하기
#### 리스트를 통한 1차원(==1행으로 구성) 배열 만들기

In [3]:
arr = np.array([1, 3, 5, 7, 9])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 3, 5, 7, 9])

### 배열의 크기
#### 'len()' 함수를 사용하여 배열의 크기를 확인 할 수 있다.

In [5]:
arr = np.array([10, 20, 30, 40, 50])
size = len(arr)

In [7]:
print("배열의 원소는 %d개 입니다" % size)

배열의 원소는 5개 입니다


### 배열의 인덱싱과 슬라이싱
#### 기본 특성이 리스트와 동일하기 때문에 인덱싱과 슬라이싱이 가능하다.

In [12]:
mydata = np.array([1, 2, 3, 4, 5])

print(mydata[0])
print(mydata[3])

1
4


In [13]:
print(mydata[1:4])

[2 3 4]


### 반복문을 통한 활용
#### 리스트와 동일하게 사용할 수 있다.

In [17]:
mydata = np.array([1, 2, 3, 4, 5])

for i, v in enumerate(mydata):
    print("%d번쨰의 원소 >> %d" % (i, v))

0번쨰의 원소 >> 1
1번쨰의 원소 >> 2
2번쨰의 원소 >> 3
3번쨰의 원소 >> 4
4번쨰의 원소 >> 5


### ndarray의 특성

In [21]:
mylist = [100, 3.14, True]
mylist

[100, 3.14, True]

In [22]:
myarr = np.array(mylist)

In [23]:
myarr

array([100.  ,   3.14,   1.  ])