# LAB 01 - Numpy Librady [1]

## #02, 'ndarray' 주요 기능

### 라이브러리 참조하기

In [1]:
import numpy as np

### 타입 지정

In [5]:
mylist1 = [100.12, 3.14, 1.5]
myarr1 = np.array(mylist1, dtype="int")
myarr1

array([100,   3,   1])

### 문자열이포함된경우의형변환

In [6]:
mylist2 = [1.2, 3, True, "4"]
myarr2 = np.array(mylist2)

In [11]:
myarr2

array(['1.2', '3', 'True', '4'], dtype='<U32')

### 리스트 타입으로 역변환

In [10]:
mylist3 = [1, 2, 3, 4, 5]
myarr3 = np.array(mylist3)
print(type(myarr3), myarr3)

mylist3_1 = list(myarr3)
print(type(mylist3_1), mylist3_1)

<class 'numpy.ndarray'> [1 2 3 4 5]
<class 'list'> [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]


### 연산자를 사용한 ndarray 연산

In [13]:
arr1 = np.array([10, 15, 20, 25, 30])
arr2 = np.array([2, 3, 4, 5, 6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [14]:
a = arr1 + arr2

In [15]:
a

array([12, 18, 24, 30, 36])

In [16]:
b = arr1 - arr2
b

array([ 8, 12, 16, 20, 24])

In [17]:
c = arr1 * arr2
c

array([ 20,  45,  80, 125, 180])

In [18]:
d = arr1 / arr2
d

array([5., 5., 5., 5., 5.])

### Numpy의함수를사용한연산

In [20]:
a = np.add(arr1, arr2)

In [21]:
a

array([12, 18, 24, 30, 36])

In [24]:
b = np.subtract(arr1, arr2)
b

array([ 8, 12, 16, 20, 24])

In [26]:
c = np.multiply(arr1, arr2)
c

array([ 20,  45,  80, 125, 180])

In [27]:
d = np.divide(arr1, arr2)
d

array([5., 5., 5., 5., 5.])

### 조건에맞는위치의원소추출

In [29]:
grade = np.array([82, 77, 91, 88])

In [31]:
grade

array([82, 77, 91, 88])

In [33]:
bool_array = np.array([True, False, True, False])
bool_array

array([ True, False,  True, False])

In [34]:
result = grade[bool_array]
result

array([82, 91])

### 조건식에따른원소추출

In [36]:
mypoint = np.array([82, 77, 91, 88])
ge80 = mypoint[mypoint >= 80]
ge80

array([82, 91, 88])

In [37]:
ge80lee90 = mypoint[np.logical_and(mypoint >= 80, mypoint <= 90)]
ge80lee90

array([82, 88])

In [38]:
gt_or_lt = mypoint[np.logical_or(mypoint < 80, mypoint > 90)]
gt_or_lt

array([77, 91])

### NumPy의조건연산

In [40]:
exam = np.array([60, 83, 75, 92, 86])

result = np.where(exam >= 80, "합격", "불합격")
result

array(['불합격', '합격', '불합격', '합격', '합격'], dtype='<U3')

### 여러 조건을 한번에 처리하기

In [43]:
exam = np.array([60, 83, 75, 92, 86])

conditions = [
    (exam >= 90),  # if
    (exam >= 80),  # elif
    (exam >= 70),  # elif
]

value = ["A", "B", "C"]

result = np.select(conditions, value, default="F")
result

array(['F', 'B', 'C', 'A', 'B'], dtype='<U1')