### 다음 조건을 모두 만족하는 파이썬 코드를 작성하시오.

NumPy의 ndarray를 활용하여
1. 정수 10,20,30,40,50으로 구성된 배열을 생성하고,
2. 배열의 길이(원소 개수)를 출력하며,
3. 배열의 첫 번째 원소와 마지막 두 개 원소를 각각 출력하고,
4. for문과 enumerate()를 이용해 인덱스와 값을 함께 출력하시오

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])

In [3]:
size = len(arr)
print(("배열의 길이: %d") % size)

배열의 길이: 5


In [4]:
print("첫 번쨰 원소:", arr[0])

첫 번쨰 원소: 10


In [5]:
print("마지막 두 개의 원소 :", arr[-2:])

마지막 두 개의 원소 : [40 50]


In [6]:
for i, v in enumerate(arr):
    print("%d번쨰 원소 >> %d 입니다" % (i, v))

0번쨰 원소 >> 10 입니다
1번쨰 원소 >> 20 입니다
2번쨰 원소 >> 30 입니다
3번쨰 원소 >> 40 입니다
4번쨰 원소 >> 50 입니다


### 성적 처리 시스템 만들기

당신은 한 학급의 성적 데이터를 NumPy로 분석해야 하는 데이터 분석가입니다.  

학생 6명의 점수 데이터가 다음과 같이 주어집니다.  

다음 조건에 따라 코드를 작성하세요.  

위 점수 리스트를 정수형ndarray 로 변환하시오.  

점수가 80점이상인학생의점수만추출하여 출력하시오.  

모든 학생에게 다음 기준으로 학점을부여하고 결과를 출력하시오.  

90점 이상 →‘A’  

80점 이상 →‘B’  

70점 이상 →‘C’  

그 외 →‘F’  

성적 처리 시스템 만들기  

score = [72.5, 88.0, 91.5, 67.0, 80.0, 59.5]

In [7]:
score = np.array([72.5, 88.0, 91.5, 67.0, 80.0, 59.5])
score

array([72.5, 88. , 91.5, 67. , 80. , 59.5])

In [8]:
arr_int = np.array(score, dtype="int")
print("원본 점수:", arr_int)

원본 점수: [72 88 91 67 80 59]


In [9]:
grade = np.where(arr_int >= 80)
grade80 = arr_int[grade]
print("80점 이상:", grade80)

80점 이상: [88 91 80]


In [10]:
conditions = [(arr_int >= 90), (arr_int >= 80), (arr_int >= 70)]

value = ["A", "B", "C"]

result = np.select(conditions, value, default="F")
print("학점 결과:", result)

학점 결과: ['C' 'B' 'A' 'F' 'B' 'F']


### AI교육생 점수 데이터 점검하기

 당신은 AI교육기관에서 수강생들의 모의시험 데이터를 검수하는 일을 맡고 있습니다.
시험 데이터는 3회차시험× 4명학생의 점수로 구성되어야 합니다. 다음 조건에 맞게
NumPy로 코드를 작성하세요.
AI교육생 점수 데이터 점검하기
1. 평균이 75, 표준편차가 5인 정규분포를 따르는 랜덤 점수 데이터를 3행 4열 배열로 생성하시오.
• 단, 결과가 재현되도록 랜덤 시드를 100으로 고정해야 함.
2. 생성된 점수 중 80점 이상인 항목만 추출하시오.
3. 점수가 저장된 배열의 차원(ndim), 형태(shape), 데이터 타입(dtype) 을 각각 출력하시오.

In [11]:
np.random.seed(100)
myarray = np.random.normal(75, 5, (3, 4))
myarray

array([[66.25117263, 76.71340202, 80.76517901, 73.73781982],
       [79.90660393, 77.57109421, 76.10589835, 69.64978335],
       [74.05252085, 76.27500722, 72.70986507, 77.17581744]])

In [12]:
result = myarray[myarray >= 80]
result

array([80.76517901])

In [13]:
print("차원:", myarray.ndim)

차원: 2


In [14]:
print("형태:", myarray.shape)

형태: (3, 4)


In [15]:
print("데이터 타입:", myarray.dtype)

데이터 타입: float64


연습문제

☐ 당신은 데이터 분석팀의 “전처리 담당자”입니다.
팀에서 전달받은 데이터는 형태도 제각각이고,타입도 일관되지 않아 분석이 어렵습니다.
☐ 아래 조건에 따라 NumPy를 이용해 데이터 타입과 구조를 정리하세요.
데이터 포맷 정리
1. 0부터 11까지의 정수를 가지는 배열을 생성하시오.
2. 이 배열을 실수형(float) 으로 변환하시오.
3. 변환된 배열을 2행 6열 구조로 재배치하시오.
4. 이후, 열의 수에 관계없이 3행으로 자동 변환되도록 𝑟𝑒𝑠ℎ𝑎𝑝𝑒() 함수를 이용하시오.
5. 마지막으로, 1차원 배열로 축소하여 결과를 출력

In [16]:
origin = np.arange(0,12)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
arrfloat = np.asarray(origin,dtype='float')

In [18]:
arrfloat

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [19]:
x = arrfloat.reshape(2,6)
x

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [20]:
y = arrfloat.reshape(3,-1)
y

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [21]:
z = arrfloat.reshape(-1)
z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])